[workspace]
members = [
    "arrow2_convert",
    "arrow2_convert_derive",
    "examples/simple"
]

[patch.crates-io]
arrow2 = { git = "https://github.com/rerun-io/arrow2", branch = "cmc/arc_datatype" }
