[package]
name = "derive-internal"
version = "0.1.0"
authors = ["Jorge Leitao <jorgecarleitao@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
keywords = ["Arrow"]

[lib]
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"
