[package]
name = "arrow2_convert_example_simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow2 = "0.16"
arrow2_convert = { version = "0.4.2", path = "../../arrow2_convert" }
