name: Check and test

on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with: 
          toolchain: beta  # FIXME: revert to stable when 1.65 lands
          components: clippy
          override: true
      - name: "clippy --all"
        run: cargo clippy --all --tests -- -D warnings

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with: 
          toolchain: beta  # FIXME: revert to stable when 1.65 lands
          override: true
          components: rustfmt
      - name: Run
        run: cargo fmt --all -- --check

  docker:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with: 
          toolchain: beta  # FIXME: revert to stable when 1.65 lands
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: taiki-e/install-action@nextest
      - name: Run
        run: |
          cargo nextest run
          cargo test --doc

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with: 
          toolchain: beta  # FIXME: revert to stable when 1.65 lands
          override: true
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - uses: Swatinem/rust-cache@v1
      - name: Generate code coverage
        run: cargo llvm-cov --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: lcov.info
          fail_ci_if_error: true
